### ISSUE TITLE
Mention changed default method for `prospectr::resample()` in NEWS

### ISSUE THREAD

**Issue by philipp-baumann** [l-ramirez-lopez/prospectr#17]
Hi Leo,

there was a change in `prospectr::resample()` which is not indicated in NEWS but would be useful to mention. Since it can be a "breaking change" for the user when no default was used for older scripts, I think it's worth a record in NEWS:

`interpol = "linear"` as default became `interpol = "spline"` as default.

Cheers,
Philipp

**Comment by l-ramirez-lopez** [comment]
Thanks Philipp
this has been now added to the NEWS
