### ISSUE TITLE
spliceCorrection bug

### ISSUE THREAD

**Issue by zecojls** [l-ramirez-lopez/prospectr#39]
Hi,

spliceCorrection does not work with a splice object length > 1, i.e., when using
`spliceCorrection(X = spectra, wav = wavelengths, splice = c(1000, 1830), interpol.bands = 10)`

Only if I pipe both slices, e.g.,
`spectra %>%  
spliceCorrection(X = ., wav = wavelengths, splice = c(1000), interpol.bands = 10) %>%  
spliceCorrection(X = ., wav = wavelengths, splice = c(1830), interpol.bands = 10)`

The console error message is:
`Error in spliceCorrection(X = as.matrix(dataset4.spectra), wav = wavelengths, : object 'index_b' not found`

When skiming over source code, I found that index_b is created only when `length(slice) == 1`.

Cheers

**Comment by l-ramirez-lopez** [comment]
thanks, 
the fix has been implemented and is now in version/branch 0.2.5
