### ISSUE TITLE
kenStone return 'Error in U %*% sqrt(D) : argumentos no compatibles' when Cumulative sum of variance is less than required

### ISSUE THREAD

**Issue by sdroldan** [l-ramirez-lopez/prospectr#41]
When `pc <1` and `any(pcsum(pvar)<pc)==FALSE` then `pc<- 1` (lines 124-128). As  `e2m()` function (called in line 133) can not process a vector (only one column matrix), return 'Error in U %*% sqrt(D) : argumentos no compatibles'. 
May be, only changing kenStone.R in line 127,` pc<-1` with `pc<-2` resolve issue. 
_I avoid making a 'Pull request' for the minimum of the proposed change_.
_Please excuse my English_

**Comment by l-ramirez-lopez** [comment]
Thanks @sdroldan for noticing this... The error can be reproduced with:
```
library(prospectr)
data(NIRsoil)
kenStone(NIRsoil$spc, k = 30, pc = 1)
```

**Comment by l-ramirez-lopez** [comment]
This issue has been solved by modifying the internal function `e2m()` which transforms the input matrix onto the Mahalanobis space using either SVD or eigendecomposition . This makes sense for matrices with more than two columns. However for a matrix of one single column, we now assume that such space is equivalent to the variable divided by the its standard deviation.
