### ISSUE TITLE
spliceCorrection

### ISSUE THREAD

**Issue by aloboa** [l-ramirez-lopez/prospectr#57]
The documentation for the splice correction in ViewSpec actually states:
"This is usually done only for presentations and documentation or when using the data to match against
a spectral library, it is not meant to correct the data."

I am confused by this final recommendation. Does it hold for prospectr::spliceCorrection() as well? I see all spectra with "no steps"...

**Comment by l-ramirez-lopez** [comment]
Dear @aloboa 
The `spliceCorrection()` function in `prospectr` is intented for spectra that originate from device sensors with multiple detectors. When the spectra (covering different spectra regions) is concatenated, at the points of transition you will usually see baseline shifts. The idea behind `spliceCorrection()` is to remove such shifts/disturbances which are not coming from the samples being analysed. In this respect the correction is not only for visualization purposes, but also for any kind of spectral analysis you need to conduct on the spectra. For example, splice correction is crucial if you need to perform any derivative processing of the spectra, without it you will get undesired artefacts in your spectra.
